name: flutter_ceaner_city_jbd
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  charts_flutter_new: ^0.12.0
  fl_chart: ^0.69.0
  webview_flutter: ^4.9.0
  url_launcher: ^6.3.0
  flutter_inappwebview: ^6.0.0
  animations: ^2.0.11
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

